### ISSUE TITLE
Compile failure with GHC 7.4.2

### ISSUE THREAD

**Issue by hvr** [jberryman/hashabler#11]
It appears that GHC 7.4.2 didn't support `PolyKinds`+`KindSignatures` everywhere yet

```
Configuring component lib from hashabler-2.0.0
Preprocessing library hashabler-2.0.0...
[1 of 4] Compiling MachDeps         ( src/MachDeps.hs, /tmp/matrix-worker/1479660360/dist-newstyle/build/x86_64-linux/ghc-7.4.2/hashabler-2.0.0/build/MachDeps.o )
[2 of 4] Compiling Data.Hashabler.Internal ( src/Data/Hashabler/Internal.hs, /tmp/matrix-worker/1479660360/dist-newstyle/build/x86_64-linux/ghc-7.4.2/hashabler-2.0.0/build/Data/Hashabler/Internal.o )

src/Data/Hashabler/Internal.hs:998:24: parse error on input `k'
```

and the line affected is

```hs
newtype TypeHash (a :: k) = TypeHash { typeHashWord :: Word64 }
    deriving (Eq, Read, Show, Bits)
```

**Comment by hvr** [comment]
Btw, is there a specific reason that `cabal-version:>=1.18` has been set in the `.cabal` file? There wasn't any significant change between 1.10 and 1.18 in the `.cabal` format, so `cabal-version:>=1.10` would suffice (and avoid problems for users with older cabal versions)

**Comment by jberryman** [comment]
Thanks for the report! I'm not sure if there's a reason the cabal version was set that way.

**Comment by jberryman** [comment]
@hvr is it important to you that we support GHC 7.4? (presumably, since you took the time to report this) I'm worried I may have removed some conditional code original in the standard hashable, which may be a chore to track down again. Really, I'd rather not so I'm just trying to see how important it is to you/others :)

**Comment by hvr** [comment]
Not important at all (a good rule of thumb is supporting at least 3 past GHC releases, and as many more as can be w/o additional effort)! :-)

Your package just got flagged by (a WIP version of) http://matrix.hackage.haskell.org/ which is basically a buildbot that looks for inaccurate package meta-data and helps us monitor the install-plan health on Hackage.

The only thing that's important is to set version bounds accurately for your build-dependencies. I.e. if you don't want to support GHC 7.4.2, just set the version constraints and/or `other-extensions` accordingly (in this case `base >= 4.6` is needed to denote GHC 7.6 and later), and the cabal solver won't be able to select GHC 7.4.2 for you package anymore. This is also generally important for e.g. the Haddock doc builder on Hackage so it doesn't run into invalid install-plans.

I've already edited existing releases' meta-data for you on Hackage (so the only thing left for you is to edit the `.cabal` file in your Git repository).

 - https://hackage.haskell.org/package/hashabler-2.0.0/revisions/
 - https://hackage.haskell.org/package/hashabler-1.3.0/revisions
 - https://hackage.haskell.org/package/hashabler-1.2.1/revisions
 - https://hackage.haskell.org/package/hashabler-1.2/revisions
 - https://hackage.haskell.org/package/hashabler-1.1/revisions

Btw, I've noticed in your `.travis.yml` file that you've managed to make use `ghcjs`; How well is that working?

**Comment by jberryman** [comment]
Oh, wow very cool, thanks a lot!

@hvr ghcjs seems miraculous, although I haven't gotten to play with it much aside from the work on this lib. It was a struggle getting it to work with travis though because building and booting the libraries took too long and travis timed out, so I had to do it piecemeal and wait for it to get put into travis' cache, then turn on my tests. (would be awesome if there was some pre-built packages in https://github.com/hvr/multi-ghc-travis ;-)

**Comment by hvr** [comment]
> ...would be awesome if there was some pre-built packages in https://github.com/hvr/multi-ghc-travis ;-)

@geraldus is working on that... :-)

**Comment by geraldus** [comment]
Yeah, guys, hold on.  I'll try to speed myself as much as possible.
